modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${license}"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/issues"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_full_name}"
    credits="${mod_credits}"
	authors="YUNGNICKYOUNG"
    description="${mod_description}"
	logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge"

[modproperties.${mod_id}]
    catalogueImageIcon="catalogue_icon.png"
    catalogueBackground="catalogue_background.png"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_loader_version_range}"

[[dependencies.${mod_id}]]
    modId="yungsapi"
    versionRange="[${mc_version}-Forge-${yungsapi_version},)"
    mandatory=true
    ordering="NONE"
    side="BOTH"