modLoader="javafml"
loaderVersion="[43,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/issues"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_full_name}"
	credits="Thanks so much to all my patrons!"
	authors="YUNGNICKYOUNG"
    description="${mod_description}"
	logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.1,)"

[[dependencies.${mod_id}]]
    modId="yungsapi"
    versionRange="[${minecraft_version}-Forge-${yungsapi_version},)"
    mandatory=true
    ordering="NONE"
    side="BOTH"