modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/issues"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_full_name}"
    credits="${mod_credits}"
	authors="YUNGNICKYOUNG"
    description="${mod_description}"
	logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-neoforge"

[modproperties.${mod_id}]
    catalogueImageIcon="catalogue_icon.png"
    catalogueBackground="catalogue_background.png"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${mc_version_range}"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering = "NONE"

[[dependencies.${mod_id}]]
    modId="yungsapi"
    versionRange="[${mc_version}-NeoForge-${yungsapi_version},)"
    type="required"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "${mod_id}.mixins.json"
